services:
  laravel_eleven_app_mysql:
    platform: "linux/amd64"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_eleven_db
      MYSQL_USER: laravel_eleven_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - laravel_eleven_mysql_data:/var/lib/mysql
    networks:
      - laravel_eleven_app_network
  web:
    image: laravel-app:latest
    build:
      target: web
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
            - laravel_eleven_app_network
    depends_on:
      - laravel_eleven_app_mysql
volumes:
    laravel_eleven_mysql_data:
        driver: local
networks:
    laravel_eleven_app_network:
        driver: bridge
        