name: CI/CD for Laravel on AWS EC2
on:
    pull_request:
        types: [opened, reopened, edited]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker Compose
                run: docker-compose -f docker-compose.yml up -d --build
            - name: Run tests
                run: docker-compose exec -T laravel_eleven_app  php artisan test
            - name: Tear down Docker Compose
                run: docker-compose down
