name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Install Docker Compose
        run: |
          sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and Push Docker Images with Docker Compose
        run: |
          docker-compose build
          docker-compose push

  deploy:
    name: 'Deploy To Production Server (AWS EC2)'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout the files'
        uses: actions/checkout@v2

      - name: 'Deploy to AWS EC2 server using SSH'
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          REMOTE_HOST:  ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.HOST_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET_DIRECTORY }}

      - name: 'Executing remote ssh commands using ssh key'
        uses: appleboy/ssh-action@master
        with:
          host:  ${{ secrets.HOST_DNS }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script:  |
            cd ${{ secrets.REMOTE_TARGET_DIRECTORY }}
            git pull origin main
