name: CI/CD for testing pipeline on Pull Requests

on:
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Install Docker Compose'
        run: |
            sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m) -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - name: 'Create .env file'
        run: |
            echo "YOUR_ENV_VARIABLE=your_value" > .env

      - name: 'Set up Docker Compose'
        run: docker-compose up -d --build --force-recreate

      - name: 'Tear down Docker Compose'
        run: docker-compose down